services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    networks:
      - mynet
    volumes:
      - ollama:/root/.ollama
    entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 5 && ollama pull llama3 && wait"]

  app:
    build: ./app
    ports:
      - "0.0.0.0:8501:8501"
    networks:
      - mynet
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama

volumes:
  ollama:

networks:
  mynet:
    driver: bridge